### ISSUE TITLE
switch and animation

### ISSUE THREAD

**Issue by KravMaguy** [KravMaguy/7111-gsap-mapbox#1]
current: logic is outside of switch, animation freezes 
expected: logic is inside of switch, animation does not freeze

comments: 
What did they decide is best behavior to do here:
https://greensock.com/forums/topic/7803-animation-reverse-not-completing-after-a-few-plays/
I think to cancel all animations on the stack if too many clicks in too short period of time

**Comment by moshfeu** [comment]
I don't actually understand the issue. Can you describe the steps in the UI I should do to see it?

**Comment by KravMaguy** [comment]
> I don't actually understand the issue. Can you describe the steps in the UI I should do to see it?

press the 3d button go to birds eye view of the building. click on one of the spaces of the building. now click on the same space many times very fast and you will see the animation get stuck, it does not revert to its initial state.  Do you see it?
