### ISSUE TITLE
tooltips and animations

### ISSUE THREAD

**Issue by KravMaguy** [KravMaguy/7111-gsap-mapbox#2]
current: the tooltip appears when the icon appears, icon link animations play at all zoom levels, dynamic links

expected: remove all tooltips at zoom level when icon appears, no animations no dynamic link functionality, default to full building spaceplan line 69
https://www.dropbox.com/s/jes3crqsk7ctypw/Screenshot%202019-11-02%2014.06.34.png?dl=0

**Comment by moshfeu** [comment]
You probably need to put the `if` condition inside the `mousemove` handler

https://github.com/KravMaguy/7111-gsap-mapbox/blob/2439d32406e554caac8de0572c212e40c2709e9f/7231.html#L978-L979

to this

```
map.on('mousemove', function (e) {
  if (map.getZoom() > 14) {
```
Because currently, you check the zoom level only once when the app is loading, but then the user may changes the zoom..

**Comment by KravMaguy** [comment]
Yes I followed your advice, it worked, but I put some follow up logic right after the if statement on line 1008-1013
https://www.dropbox.com/s/46ow94j4nirskaj/Screenshot%202019-11-03%2009.06.09.png?dl=0

This is for a case where the user had clicked or hovered a certain spot and then pinch zoomed out without moving the mouse, so the tooltip would actually still be showing even if he zoomed out past level 14. But now that tooltip thats left hanging around will disappear but only when he starts moving the mouse again. It does solve the problem of that tooltip hanging around, but is it better to put that logic somewhere in this on zoom block instead :
https://www.dropbox.com/s/06v7riyashtqcsp/Screenshot%202019-11-03%2009.09.16.png?dl=0

so it will actually just check on zooming action and not when the client is moving the mouse.
